### ISSUE TITLE
Feature Parity with C Mega TODO

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/firmware-rs#1]
- [x] vl6180x driver, first sync then async
- [x] Add a usart print in different threads
- [x] hook up adc and create C-matching yet compile time checking way of implementing float to int.

General devops
- [ ] Investigate defmt capabilities and `cargo embed` for gdb-like server
- [ ] Fully document standards, practices, etc.
- [ ] Prepare embassy versioning standards
- [x] Add github actions and cross platform guides
- [ ] Add deployment troubleshooting and more
